version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravel-app
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
    - location: scripts/set_permissions.sh
